parameterTypes = [
  {
    "_match": "tint.r",
    "_name": "ColorRGB_Red",
    "_prettyName": "R",
    "_feature": "Color.Indirect",
    "_ActivationGroup": "ColorIndirect",
    "definition": "",
    "explanation": "",
    "visual": "",
    "_label": "Red Tint"
  },
  {
    "_match": "tint.g",
    "_name": "ColorRGB_Green",
    "_prettyName": "G",
    "_feature": "Color.Indirect",
    "_ActivationGroup": "ColorIndirect",
    "definition": "",
    "explanation": "",
    "visual": "",
    "_label": "Green Tint"
  },
  {
    "_match": "tint.b",
    "_name": "ColorRGB_Blue",
    "_prettyName": "B",
    "_feature": "Color.Indirect",
    "_ActivationGroup": "ColorIndirect",
    "definition": "",
    "explanation": "",
    "visual": "",
    "_label": "Blue Tint"
  },
  {
    "_match": "brightness",
    "_name": "Dimmer",
    "_prettyName": "Dim",
    "_feature": "Dimmer.Dimmer",
    "definition": "Controls the intensity of a fixture.",
    "explanation": "Gradual (fading) change of intensity or brightness or in some cases even opacity shall be controlled with this attribute. Physical values go from 0 = no output, to 1 = full output. If a software makes use of an overall intensity control such as a grandmaster, it is important for the application to understand which attribute to change. In that scenario the dimmer attribute shall be the main intensity, brightness or opacity change.",
    "visual": "",
    "_label": "Dimmer"
  },
  {
    "_match": "video.bank",
    "_name": "MediaBank",
    "_prettyName": "Media Bank",
    "_feature": "Gobo.Media",
    "definition": "Selects bank that contains media content.",
    "explanation": "",
    "visual": "",
    "_label": "Media Bank"
  },
  {
    "_match": "video.slot",
    "_name": "MediaSlot",
    "_prettyName": "Media Slot",
    "_feature": "Gobo.Media",
    "definition": "Selects the slot that contains media content.",
    "explanation": "",
    "visual": "",
    "_label": "Media Slot"
  },
  {
    "_match": "mapping.bank",
    "_name": "MappingBank",
    "_prettyName": "Map Bank",
    "_feature": "Gobo.Media",
    "definition": "Selects bank for mapping",
    "explanation": "",
    "visual": "",
    "_label": "Mapping Bank"
  },
  {
    "_match": "mapping.slot",
    "_name": "MappingSlot",
    "_prettyName": "Map Slot",
    "_feature": "Gobo.Media",
    "definition": "Selects slot for mapping",
    "explanation": "",
    "visual": "",
    "_label": "Mapping Slot"
  },
  {
    "_match": "speed",
    "_name": "PlaySpeed",
    "_prettyName": "Speed",
    "_feature": "Gobo.Media",
    "definition": "Adjusts playback speed of media content.",
    "explanation": "Use this attribute to control the speed of media content playback",
    "visual": "",
    "_label": "Media Play Speed"
  },
  {
    "_match": "mode",
    "_name": "Playmode",
    "_prettyName": "Mode",
    "_feature": "Gobo.Media",
    "definition": "",
    "explanation": "For devices that allow to set a mode of media playback, for example play and loop, play and stop..., use  this attribute to describe this behavior.",
    "visual": "",
    "_label": "Media Playmode"
  },
  {
    "_match": "at end point",
    "_name": "Looping",
    "_prettyName": "Loop",
    "_feature": "Gobo.Media",
    "definition": "",
    "explanation": "Looping behavior at end point.",
    "visual": "",
    "_label": "Media Looping"
  },
  {
    "_match": "Output.bank",
    "_name": "AudioOutputBank",
    "_prettyName": "Audio Bank",
    "_feature": "Gobo.Media",
    "definition": "",
    "explanation": "Bank of Audio Device",
    "visual": "",
    "_label": "Audio Output Device Bank"
  },
  {
    "_match": "Output.slot",
    "_name": "AudioOutputSlot",
    "_prettyName": "Audio Slot",
    "_feature": "Gobo.Media",
    "definition": "",
    "explanation": "Slot of Audio Device",
    "visual": "",
    "_label": "Audio Output Device Slot"
  },
  {
    "_match": "brightness (shift)",
    "_name": "Brightness",
    "_prettyName": "B",
    "_feature": "Color.HSBC_Shift",
    "definition": "Adjusts brightness of content.",
    "explanation": "Use this attribute to describe a function that allows to set brightness of media content.",
    "visual": "",
    "_label": "Video Brightness"
  },
  {
    "_match": "blendMode",
    "_name": "BlendMode",
    "_prettyName": "Blend",
    "_feature": "Gobo.Media",
    "_physicalUnit": "None",
    "definition": "Defines mode of video blending.",
    "explanation": "Use this attribute to describe a function that allows to choose a mode of blending of a video output.",
    "visual": "",
    "_label": "Video Blend Mode"
  },
  {
    "_match": "transition time",
    "_name": "TransitionTime",
    "_prettyName": "XFTime",
    "_feature": "Gobo.Media",
    "_physicalUnit": "None",
    "definition": "",
    "explanation": "",
    "visual": "",
    "_label": "Transition Time"
  },
  {
    "_match": "contrast (scale)",
    "_name": "Contrast",
    "_prettyName": "C",
    "_feature": "Color.HSBC_Shift",
    "definition": "Adjusts contrast of content.",
    "explanation": "",
    "visual": "",
    "_label": "Video Contrast"
  },
  {
    "_match": "saturation scale",
    "_name": "Saturation",
    "_prettyName": "S",
    "_feature": "Color.HSBC_Shift",
    "definition": "Adjusts saturation of content.",
    "explanation": "",
    "visual": "",
    "_label": "Video Saturation"
  },
  {
    "_match": "hue shift",
    "_name": "HueShift",
    "_prettyName": "H",
    "_feature": "Color.HSBC_Shift",
    "_physicalUnit": "Angle",
    "definition": "Adjusts color hue shift of content.",
    "explanation": "",
    "visual": "",
    "_label": "Video Hue Shift"
  },
  {
    "_match": "RGB controlled",
    "_name": "ColourShiftMode",
    "_prettyName": "CSMode",
    "_feature": "Color.Colourshift",
    "definition": "Ganged or individual colorshifting",
    "explanation": "Ganged or individual colorshifting.",
    "visual": "",
    "_label": "Colour Shift Mode"
  },
  {
    "_match": "red min",
    "_name": "RedMinimum",
    "_prettyName": "R Min",
    "_feature": "Color.Colourshift",
    "definition": "Red Minimum",
    "explanation": "Ganged or Red minimum.",
    "visual": "",
    "_label": "Red Minimum"
  },
  {
    "_match": "red max",
    "_name": "RedMaximum",
    "_prettyName": "R Max",
    "_feature": "Color.Colourshift",
    "definition": "Red Maximum",
    "explanation": "Ganged or Red maximum.",
    "visual": "",
    "_label": "Red Maximum"
  },
  {
    "_match": "red gamma",
    "_name": "RedGamma",
    "_prettyName": "R Gamma",
    "_feature": "Color.Colourshift",
    "definition": "Red Maximum",
    "explanation": "Ganged or Red maximum.",
    "visual": "",
    "_label": "Red Maximum"
  },
  {
    "_match": "green min",
    "_name": "GreenMinimum",
    "_prettyName": "G Min",
    "_feature": "Color.Colourshift",
    "definition": "Green Minimum",
    "explanation": "Green minimum.",
    "visual": "",
    "_label": "Green Minimum"
  },
  {
    "_match": "green max",
    "_name": "GreenMaximum",
    "_prettyName": "G Max",
    "_feature": "Color.Colourshift",
    "definition": "Green Maximum",
    "explanation": "Green maximum.",
    "visual": "",
    "_label": "Green Maximum"
  },
  {
    "_match": "green gamma",
    "_name": "GreenGamma",
    "_prettyName": "G Gamma",
    "_feature": "Color.Colourshift",
    "definition": "Green Maximum",
    "explanation": "Green maximum.",
    "visual": "",
    "_label": "Green Maximum"
  },
  {
    "_match": "blue min",
    "_name": "BlueMinimum",
    "_prettyName": "B Min",
    "_feature": "Color.Colourshift",
    "definition": "Blue Minimum",
    "explanation": "Blue minimum.",
    "visual": "",
    "_label": "Blue Minimum"
  },
  {
    "_match": "blue max",
    "_name": "BlueMaximum",
    "_prettyName": "B Max",
    "_feature": "Color.Colourshift",
    "definition": "Blue Maximum",
    "explanation": "Blue maximum.",
    "visual": "",
    "_label": "Blue Maximum"
  },
  {
    "_match": "blue gamma",
    "_name": "BlueGamma",
    "_prettyName": "B Gamma",
    "_feature": "Color.Colourshift",
    "definition": "Blue Maximum",
    "explanation": "Blue maximum.",
    "visual": "",
    "_label": "Blue Gamma"
  },
  {
    "_match": "key colour.r",
    "_name": "VideoKey_R",
    "_prettyName": "R",
    "_feature": "Color.ColorKey",
    "_Color": "0.64,0.33,21.3",
    "definition": "Adjusts red color for color keying.",
    "explanation": "",
    "visual": "",
    "_label": "Video Key Color Red"
  },
  {
    "_match": "key colour.g",
    "_name": "VideoKey_G",
    "_prettyName": "G",
    "_feature": "Color.ColorKey",
    "_Color": "0.3,0.6,71.5",
    "definition": "Adjusts green color for color keying.",
    "explanation": "",
    "visual": "",
    "_label": "Video Key Color Green"
  },
  {
    "_match": "key colour.b",
    "_name": "VideoKey_B",
    "_prettyName": "B",
    "_feature": "Color.ColorKey",
    "_Color": "0.15,0.06,7.2",
    "definition": "",
    "explanation": "",
    "visual": "",
    "_label": "Video Color Key Blue"
  },
  {
    "_match": "hardness",
    "_name": "VideoKeyHardness",
    "_prettyName": "Hard",
    "_feature": "Color.ColorKey",
    "definition": "Adjusts hardness of color keying.",
    "explanation": "",
    "visual": "",
    "_label": "Video Key Hardness"
  },
  { "_match": "threshold",
    "_name": "Threshold",
    "_prettyName": "Thresh",
    "_feature": "Color.ColorKey",
    "definition": "Adjusts threshold of color keying.",
    "explanation": "",
    "visual": "",
    "_label": "Video Key Threshold"
  },
  {
    "_match": "clip_type",
    "_name": "MediaFit",
    "_prettyName": "Fit",
    "_feature": "Gobo.Media",
    "definition": "",
    "explanation": "Defines how media is scaled to the screen.",
    "visual": "",
    "_label": "Media Fit Clipping"
  },
  {
    "_match": "size",
    "_name": "Size",
    "_prettyName": "Size",
    "_feature": "Position.Scale",
    "_ActivationGroup": "Scale_XYZ",
    "definition": "Unified scaling on all axis.",
    "explanation": "Use this attribute to describe a function that scales the percentage of movement on all X and Y axes.",
    "visual": "",
    "_label": "Size"
  },
  {
    "_match": "scale.x",
    "_name": "ScaleX",
    "_prettyName": "Scale X",
    "_feature": "Position.Scale",
    "_ActivationGroup": "Scale_XYZ",
    "definition": "Scaling on X axis.",
    "explanation": "Use this attribute to describe a function that scales the percentage of movement on an X axis.",
    "visual": "",
    "_label": "Scale X"
  },
  {
    "_match": "scale.y",
    "_name": "ScaleY",
    "_prettyName": "Scale Y",
    "_feature": "Position.Scale",
    "_ActivationGroup": "Scale_XYZ",
    "definition": "Scaling on Y axis.",
    "explanation": "Use this attribute to describe a function that scales the percentage of movement on an Y axis.",
    "visual": "",
    "_label": "Scale Y"
  },
  {
    "_match": "pos.x",
    "_name": "XYZ_X",
    "_prettyName": "X",
    "_feature": "Position.XYZ",
    "_ActivationGroup": "XYZ",
    "definition": "Defines a fixture's x-coordinate within an XYZ coordinate system.",
    "explanation": "Devices that can move straight in X-direction in space (opposite to pan or tilt circular movement) describe the movement with this attribute. A typical usage is left/right movement of a video-layer in space.",
    "visual": "",
    "_label": "XYZ X"
  },
  {
    "_match": "pos.y",
    "_name": "XYZ_Y",
    "_prettyName": "Y",
    "_feature": "Position.XYZ",
    "_ActivationGroup": "XYZ",
    "definition": "Defines a fixture's y-coordinate within an XYZ coordinate system.",
    "explanation": "Devices that can move straight in Y-direction in space (opposite to pan or tilt circular movement) describe the movement with this attribute. A typical usage is forward/backward movement of a video-layer in space.",
    "visual": "",
    "_label": "XYZ Y"
  },
  {
    "_match": "rotation",
    "_name": "Rotation",
    "_prettyName": "Rot",
    "_feature": "Position.Rotation",
    "_physicalUnit": "Angle",
    "definition": "Content rotation.",
    "explanation": "Content Rotation.",
    "visual": "",
    "_label": "Rot X"
  },
  {
    "_match": "left",
    "_name": "CropLeft",
    "_prettyName": "L",
    "_feature": "Shapers.Shapers",
    "_ActivationGroup": "Shaper",
    "definition": "Crop that shape the top/right/bottom/left of the beam.",
    "explanation": "Cropping edge of raster",
    "visual": "",
    "_label": "Crop Left"
  },
  {
    "_match": "right",
    "_name": "CropRight",
    "_prettyName": "R",
    "_feature": "Shapers.Shapers",
    "_ActivationGroup": "Shaper",
    "definition": "Crop that shape the top/right/bottom/left of the beam.",
    "explanation": "Cropping edge of raster",
    "visual": "",
    "_label": "Crop Right"
  },
  {
    "_match": "top",
    "_name": "CropTop",
    "_prettyName": "T",
    "_feature": "Shapers.Shapers",
    "_ActivationGroup": "Shaper",
    "definition": "Crop that shape the top/right/bottom/left of the beam.",
    "explanation": "Cropping edge of raster",
    "visual": "",
    "_label": "Crop Top"
  },
  {
    "_match": "bottom",
    "_name": "CropBottom",
    "_prettyName": "B",
    "_feature": "Shapers.Shapers",
    "_ActivationGroup": "Shaper",
    "definition": "Crop that shape the top/right/bottom/left of the beam.",
    "explanation": "Cropping edge of raster",
    "visual": "",
    "_label": "Crop Bottom"
  },
  {
    "_match": "cropSoftness",
    "_name": "CropSoftness",
    "_prettyName": "Soft",
    "_feature": "Shapers.Shapers",
    "_ActivationGroup": "Shaper",
    "definition": "Softness of crop.",
    "explanation": "Softness of crop.",
    "visual": "",
    "_label": "Crop Softness"
  },
  {
    "_match": "on clock lost",
    "_name": "TCLost",
    "_prettyName": "TCLost",
    "_feature": "Time.Timecode",
    "_ActivationGroup": "Timecode",
    "definition": "",
    "explanation": "",
    "visual": "",
    "_label": "ON TC Lost"
  },
  {
    "_match": "hours",
    "_name": "Hours",
    "_prettyName": "H",
    "_feature": "Time.Timecode",
    "_ActivationGroup": "Timecode",
    "definition": "",
    "explanation": "",
    "visual": "",
    "_label": "Hours"
  },
  {
    "_match": "minutes",
    "_name": "Minutes",
    "_prettyName": "M",
    "_feature": "Time.Timecode",
    "_ActivationGroup": "Timecode",
    "definition": "",
    "explanation": "",
    "visual": "",
    "_label": "Minutes"
  },
  {
    "_match": "seconds",
    "_name": "Seconds",
    "_prettyName": "S",
    "_feature": "Time.Timecode",
    "_ActivationGroup": "Timecode",
    "definition": "",
    "explanation": "",
    "visual": "",
    "_label": "Seconds"
  },
  {
    "_match": "frames",
    "_name": "Frames",
    "_prettyName": "F",
    "_feature": "Time.Timecode",
    "_ActivationGroup": "Timecode",
    "definition": "",
    "explanation": "",
    "visual": "",
    "_label": "Frames"
  },
  {
    "_match": "frame index",
    "_name": "FrameIndex",
    "_prettyName": "FIndex",
    "_feature": "Time.Time",
    "_ActivationGroup": "Time",
    "definition": "",
    "explanation": "",
    "visual": "",
    "_label": "Frame Index"
  },
  {
    "_match": "trim frames",
    "_name": "TrimFrames",
    "_prettyName": "TrimF",
    "_feature": "Time.Time",
    "_ActivationGroup": "Time",
    "definition": "",
    "explanation": "",
    "visual": "",
    "_label": "Trim Frames"
  },
  {
    "_match": "loop inFrame",
    "_name": "LoopInFrame",
    "_prettyName": "TLInF",
    "_feature": "Time.Time",
    "_ActivationGroup": "Time",
    "definition": "",
    "explanation": "",
    "visual": "",
    "_label": "Loop In Frames"
  },
  {
    "_match": "loop outFrame",
    "_name": "LoopOutFrame",
    "_prettyName": "TLOutF",
    "_feature": "Time.Time",
    "_ActivationGroup": "Time",
    "definition": "",
    "explanation": "",
    "visual": "",
    "_label": "Loop Out Frame"
  },
  {
    "_match": "volume",
    "_name": "VideoSoundVolume",
    "_prettyName": "Volume",
    "_feature": "Video.Video",
    "definition": "Adjusts sound volume.",
    "explanation": "Describes the audio volume function of a device.",
    "visual": "",
    "_label": "Video Sound Volume"
  },
  {
    "_match": "acesExposure",
    "_name": "AcesExposure",
    "_prettyName": "Exposure",
    "_feature": "Color.Aces",
    "definition": "",
    "explanation": "",
    "visual": "",
    "_label": "Aces Exposure"
  },
  {
    "_match": "acesGamma",
    "_name": "AcesGamma",
    "_prettyName": "Gamma",
    "_feature": "Color.Aces",
    "definition": "",
    "explanation": "",
    "visual": "",
    "_label": "Aces Gamma"
  },
  {
    "_match": "cdl.bank",
    "_name": "CDLBank",
    "_prettyName": "Bank",
    "_feature": "Color.CDL",
    "definition": "",
    "explanation": "",
    "visual": "",
    "_label": "CDL Bank"
  },
  {
    "_match": "cdl.slot",
    "_name": "CDLSlot",
    "_prettyName": "Slot",
    "_feature": "Color.CDL",
    "definition": "",
    "explanation": "",
    "visual": "",
    "_label": "CDL Slot"
  },
  {
    "_match": "ocioExposure",
    "_name": "OCIOExposure",
    "_prettyName": "Exposure",
    "_feature": "Color.OCIO",
    "definition": "",
    "explanation": "",
    "visual": "",
    "_label": "OCIO Exposure"
  },
  {
    "_match": "ocioContrast",
    "_name": "OCIOContrast",
    "_prettyName": "Contrast",
    "_feature": "Color.OCIO",
    "definition": "",
    "explanation": "",
    "visual": "",
    "_label": "OCIO Contrast"
  },
  {
    "_match": "ocioGamma",
    "_name": "OCIOGamma",
    "_prettyName": "Gamma",
    "_feature": "Color.OCIO",
    "definition": "",
    "explanation": "",
    "visual": "",
    "_label": "OCIO Gamma"
  }
]
